// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { GetPhotosSummaryData, GetPhotosSummaryResponses, GetGalleryRootData, GetGalleryRootResponses, ResetGalleryRootData, ResetGalleryRootResponses, GetTracksSummaryData, GetTracksSummaryResponses, InspectPgxFileData, InspectPgxFileResponses, InspectPgxFileErrors, GetFilesystemSummaryData, GetFilesystemSummaryResponses, FindPhotosData, FindPhotosResponses, FindPhotosErrors, FindGpxFilesData, FindGpxFilesResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class Photos {
    /**
     * Get Photos Summary
     */
    public static getPhotosSummary<ThrowOnError extends boolean = false>(options?: Options<GetPhotosSummaryData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetPhotosSummaryResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/photos',
            ...options
        });
    }
}

export class Settings {
    /**
     * Get Gallery Root
     */
    public static getGalleryRoot<ThrowOnError extends boolean = false>(options?: Options<GetGalleryRootData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetGalleryRootResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/settings/gallery-root',
            ...options
        });
    }
    
    /**
     * Reset Gallery Root
     */
    public static resetGalleryRoot<ThrowOnError extends boolean = false>(options?: Options<ResetGalleryRootData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<ResetGalleryRootResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/settings/gallery-root/reset',
            ...options
        });
    }
}

export class Tracks {
    /**
     * Get Tracks Summary
     */
    public static getTracksSummary<ThrowOnError extends boolean = false>(options?: Options<GetTracksSummaryData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetTracksSummaryResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/tracks',
            ...options
        });
    }
    
    /**
     * Inspect Gpx File
     */
    public static inspectPgxFile<ThrowOnError extends boolean = false>(options: Options<InspectPgxFileData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<InspectPgxFileResponses, InspectPgxFileErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/tracks/inspect/{gpx_file}',
            ...options
        });
    }
}

export class Filesystem {
    /**
     * Slg Filesystem Summary
     */
    public static getFilesystemSummary<ThrowOnError extends boolean = false>(options?: Options<GetFilesystemSummaryData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetFilesystemSummaryResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/fs',
            ...options
        });
    }
    
    /**
     * Find Files In Folder
     * Find photos in a specific folder
     */
    public static findPhotos<ThrowOnError extends boolean = false>(options: Options<FindPhotosData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<FindPhotosResponses, FindPhotosErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/fs/photos/{path}',
            ...options
        });
    }
    
    /**
     * Find Gpx Files
     * Find GPX files in gallery root
     */
    public static findGpxFiles<ThrowOnError extends boolean = false>(options?: Options<FindGpxFilesData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<FindGpxFilesResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/fs/gpx',
            ...options
        });
    }
}