// This file is auto-generated by @hey-api/openapi-ts

/**
 * FileSystemSummary
 */
export type FileSystemSummary = {
    /**
     * Folders
     */
    folders: Array<FolderSummary>;
    /**
     * Gpx Files Count
     */
    gpx_files_count: number;
};

/**
 * FolderSummary
 */
export type FolderSummary = {
    /**
     * Folder
     */
    folder: string;
    /**
     * Total Photos
     */
    total_photos: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * PhotoSummary
 */
export type PhotoSummary = {
    /**
     * Folder
     */
    folder: string;
    /**
     * Total Photos
     */
    total_photos: number;
    /**
     * First Taken At
     */
    first_taken_at: string;
    /**
     * Last Taken At
     */
    last_taken_at: string;
};

/**
 * TrackSummary
 */
export type TrackSummary = {
    /**
     * Uid
     */
    uid: string;
    /**
     * Name
     */
    name: string;
    /**
     * Total Points
     */
    total_points: number;
    /**
     * Start Time
     */
    start_time: string;
    /**
     * Finish Time
     */
    finish_time: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetPhotosSummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/photos';
};

export type GetPhotosSummaryResponses = {
    /**
     * Response Get Photos Summary
     * Successful Response
     */
    200: Array<PhotoSummary>;
};

export type GetPhotosSummaryResponse = GetPhotosSummaryResponses[keyof GetPhotosSummaryResponses];

export type GetGalleryRootData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/settings/gallery-root';
};

export type GetGalleryRootResponses = {
    /**
     * Response Get Gallery Root
     * Successful Response
     */
    200: string;
};

export type GetGalleryRootResponse = GetGalleryRootResponses[keyof GetGalleryRootResponses];

export type ResetGalleryRootData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/settings/gallery-root/reset';
};

export type ResetGalleryRootResponses = {
    /**
     * Response Reset Gallery Root
     * Successful Response
     */
    200: string;
};

export type ResetGalleryRootResponse = ResetGalleryRootResponses[keyof ResetGalleryRootResponses];

export type GetTracksSummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tracks';
};

export type GetTracksSummaryResponses = {
    /**
     * Response Get Tracks Summary
     * Successful Response
     */
    200: Array<TrackSummary>;
};

export type GetTracksSummaryResponse = GetTracksSummaryResponses[keyof GetTracksSummaryResponses];

export type GetFilesystemSummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/fs';
};

export type GetFilesystemSummaryResponses = {
    /**
     * Successful Response
     */
    200: FileSystemSummary;
};

export type GetFilesystemSummaryResponse = GetFilesystemSummaryResponses[keyof GetFilesystemSummaryResponses];

export type GetFolderPhotosData = {
    body?: never;
    path: {
        /**
         * Path
         */
        path: string;
    };
    query?: never;
    url: '/api/v1/fs/{path}';
};

export type GetFolderPhotosErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetFolderPhotosError = GetFolderPhotosErrors[keyof GetFolderPhotosErrors];

export type GetFolderPhotosResponses = {
    /**
     * Response Get Folder Photos
     * Successful Response
     */
    200: Array<string>;
};

export type GetFolderPhotosResponse = GetFolderPhotosResponses[keyof GetFolderPhotosResponses];

export type ClientOptions = {
    baseURL: 'http://localhost:8000' | (string & {});
};