// This file is auto-generated by @hey-api/openapi-ts

/**
 * PhotoSummary
 */
export type PhotoSummary = {
    /**
     * Path
     */
    path: string;
    /**
     * Total Photos
     */
    total_photos: number;
    /**
     * First Taken At
     */
    first_taken_at: string;
    /**
     * Last Taken At
     */
    last_taken_at: string;
};

export type GetApiV1PhotosData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/photos/';
};

export type GetApiV1PhotosResponses = {
    /**
     * Response Photos-Get Photos Summary
     * Successful Response
     */
    200: Array<PhotoSummary>;
};

export type GetApiV1PhotosResponse = GetApiV1PhotosResponses[keyof GetApiV1PhotosResponses];

export type ClientOptions = {
    baseURL: 'http://localhost:8000' | (string & {});
};