// This file is auto-generated by @hey-api/openapi-ts

import { type Options, Filesystem } from '../../sdk.gen';
import type { _JSONValue, UseQueryOptions } from '@pinia/colada';
import type { GetSummaryData, GetSummaryResponse, GetFolderPhotosData, GetFolderPhotosError, GetFolderPhotosResponse } from '../../types.gen';
import type { AxiosError } from 'axios';
import { client as _heyApiClient } from '../../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'body' | 'path'> & {
        _id: string;
        baseURL?: _JSONValue;
        headers?: _JSONValue;
        query?: _JSONValue;
        tags?: _JSONValue;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? _heyApiClient).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (tags) {
        params.tags = tags as unknown as undefined;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers as unknown as undefined;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query as unknown as undefined;
    }
    return [
        params
    ];
};

export const getSummaryQueryKey = (options?: Options<GetSummaryData>) => createQueryKey('getSummary', options, [
    'filesystem'
]);

/**
 * Slg Filesystem Summary
 */
export const getSummaryQuery = (options?: Options<GetSummaryData>): UseQueryOptions<GetSummaryResponse, AxiosError<Error>> => {
    return {
        key: getSummaryQueryKey(options),
        query: async (context) => {
            const { data } = await Filesystem.getSummary({
                ...options,
                ...context,
                throwOnError: true
            });
            return data;
        }
    };
};

export const getFolderPhotosQueryKey = (options: Options<GetFolderPhotosData>) => createQueryKey('getFolderPhotos', options, [
    'filesystem'
]);

/**
 * Get Files In Folder
 * Get list of photos or gpx files in a specific folder
 */
export const getFolderPhotosQuery = (options: Options<GetFolderPhotosData>): UseQueryOptions<GetFolderPhotosResponse, AxiosError<GetFolderPhotosError>> => {
    return {
        key: getFolderPhotosQueryKey(options),
        query: async (context) => {
            const { data } = await Filesystem.getFolderPhotos({
                ...options,
                ...context,
                throwOnError: true
            });
            return data;
        }
    };
};