// This file is auto-generated by @hey-api/openapi-ts

import { type Options, Settings } from '../../sdk.gen';
import type { _JSONValue, UseQueryOptions, UseMutationOptions } from '@pinia/colada';
import type { GetGalleryRootData, GetGalleryRootResponse, ResetGalleryRootData, ResetGalleryRootResponse } from '../../types.gen';
import type { AxiosError } from 'axios';
import { client as _heyApiClient } from '../../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'body' | 'path'> & {
        _id: string;
        baseURL?: _JSONValue;
        headers?: _JSONValue;
        query?: _JSONValue;
        tags?: _JSONValue;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? _heyApiClient).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (tags) {
        params.tags = tags as unknown as undefined;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers as unknown as undefined;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query as unknown as undefined;
    }
    return [
        params
    ];
};

export const getGalleryRootQueryKey = (options?: Options<GetGalleryRootData>) => createQueryKey('getGalleryRoot', options, [
    'settings'
]);

/**
 * Get Gallery Root
 */
export const getGalleryRootQuery = (options?: Options<GetGalleryRootData>): UseQueryOptions<GetGalleryRootResponse, AxiosError<Error>> => {
    return {
        key: getGalleryRootQueryKey(options),
        query: async (context) => {
            const { data } = await Settings.getGalleryRoot({
                ...options,
                ...context,
                throwOnError: true
            });
            return data;
        }
    };
};

/**
 * Reset Gallery Root
 */
export const resetGalleryRootMutation = (options?: Options<ResetGalleryRootData>): UseMutationOptions<ResetGalleryRootResponse, Options<ResetGalleryRootData>, AxiosError<Error>> => {
    return {
        mutation: async (fnOptions) => {
            const { data } = await Settings.resetGalleryRoot({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
};