// This file is auto-generated by @hey-api/openapi-ts

import { type Options, Tracks } from '../../sdk.gen';
import type { _JSONValue, UseQueryOptions, UseMutationOptions } from '@pinia/colada';
import type { GetTracksSummaryData, GetTracksSummaryResponse, InspectGpxFileData, InspectGpxFileError, InspectGpxFileResponse, ImportPgxFileData, ImportPgxFileError, ImportPgxFileResponse, LocatePhotoOnTrackData, LocatePhotoOnTrackError, LocatePhotoOnTrackResponse } from '../../types.gen';
import type { AxiosError } from 'axios';
import { client as _heyApiClient } from '../../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'body' | 'path'> & {
        _id: string;
        baseURL?: _JSONValue;
        headers?: _JSONValue;
        query?: _JSONValue;
        tags?: _JSONValue;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? _heyApiClient).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (tags) {
        params.tags = tags as unknown as undefined;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers as unknown as undefined;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query as unknown as undefined;
    }
    return [
        params
    ];
};

export const getTracksSummaryQueryKey = (options?: Options<GetTracksSummaryData>) => createQueryKey('getTracksSummary', options, [
    'tracks'
]);

/**
 * Get Tracks Summary
 */
export const getTracksSummaryQuery = (options?: Options<GetTracksSummaryData>): UseQueryOptions<GetTracksSummaryResponse, AxiosError<Error>> => {
    return {
        key: getTracksSummaryQueryKey(options),
        query: async (context) => {
            const { data } = await Tracks.getTracksSummary({
                ...options,
                ...context,
                throwOnError: true
            });
            return data;
        }
    };
};

export const inspectGpxFileQueryKey = (options: Options<InspectGpxFileData>) => createQueryKey('inspectGpxFile', options, [
    'tracks'
]);

/**
 * Inspect Gpx File
 */
export const inspectGpxFileQuery = (options: Options<InspectGpxFileData>): UseQueryOptions<InspectGpxFileResponse, AxiosError<InspectGpxFileError>> => {
    return {
        key: inspectGpxFileQueryKey(options),
        query: async (context) => {
            const { data } = await Tracks.inspectGpxFile({
                ...options,
                ...context,
                throwOnError: true
            });
            return data;
        }
    };
};

/**
 * Import Gpx File Into Db
 */
export const importPgxFileMutation = (options: Options<ImportPgxFileData>): UseMutationOptions<ImportPgxFileResponse, Options<ImportPgxFileData>, AxiosError<ImportPgxFileError>> => {
    return {
        mutation: async (fnOptions) => {
            const { data } = await Tracks.importPgxFile({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
};

/**
 * Locate Photo On Track
 */
export const locatePhotoOnTrackMutation = (options: Options<LocatePhotoOnTrackData>): UseMutationOptions<LocatePhotoOnTrackResponse, Options<LocatePhotoOnTrackData>, AxiosError<LocatePhotoOnTrackError>> => {
    return {
        mutation: async (fnOptions) => {
            const { data } = await Tracks.locatePhotoOnTrack({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
};