/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    '[[folder]]+': typeof import('./components/[[folder]]+.vue')['default']
    FsPhotos: typeof import('./components/FsPhotos.vue')['default']
    FsTracks: typeof import('./components/FsTracks.vue')['default']
    GalleryDrawerContent: typeof import('./components/GalleryDrawerContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TrackMap: typeof import('./components/TrackMap.vue')['default']
  }
}
